services:
  # Backend FastAPI
  - type: web
    name: nutrisnap-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_PATH
        value: serviceAccountKey.json

  # Frontend Streamlit
  - type: web
    name: nutrisnap-frontend
    env: python
    buildCommand: pip install -r requirements-frontend.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        fromService:
          name: nutrisnap-backend
          type: web
          property: host
